sys:
  users:
    - username: 13632672222
      password: 123456
      age: 22
      nickName: 张三
logging:
  level:
    com:
      qchery:
        funda: debug
jasypt:
  encryptor:
    password: funda
    algorithm: PBEWithMD5AndDES
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: qinrui
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.qchery.funda.modules
endpoints:
  shutdown:
    enabled: true
    path: /xxx
server:
  port: 9000
management:
  security:
    enabled: true
  port: 9001
  address: 127.0.0.1
security:
  basic:
    path: /xxx
    enabled: false
  user:
    name: root
    password: 123456